In [1]:
import torch

In [ ]:
a = torch.empty(3, 4)

In [ ]:
a

tensor([[-2.3150e+17,  3.0709e-41,  3.3631e-44,  0.0000e+00],
        [        nan,  3.0709e-41,  1.1578e+27,  1.1362e+30],
        [ 7.1547e+22,  4.5828e+30,  1.2121e+04,  7.1846e+22]])

In [ ]:
b = torch.rand(3,4)
b

tensor([[0.2028, 0.0392, 0.0886, 0.1750],
        [0.8132, 0.1562, 0.9148, 0.7332],
        [0.0750, 0.7476, 0.8698, 0.4103]])

In [ ]:
c = torch.zeros(3,3) 

In [ ]:
c

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [ ]:
d = torch.tensor([[1, 2, 3], [4, 5, 6]])
d 

tensor([[1, 2, 3],
        [4, 5, 6]])

In [ ]:
e  = d.new_ones()
e

TypeError: ignored

In [ ]:
e = d.new_ones(3,3)
e

tensor([[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]])

In [ ]:
f = torch.rand_like(e)
f

RuntimeError: ignored

In [ ]:
f = torch.rand_like(e, dtype=torch.long)
f

RuntimeError: ignored

In [ ]:
f = torch.rand_like(e, dtype=torch.float)
f

tensor([[0.9688, 0.6473, 0.4705],
        [0.1528, 0.1498, 0.8278],
        [0.5898, 0.6950, 0.7501]])

In [ ]:
a = torch.rand(4,3,2)
print(a)
print(a.size())

tensor([[[0.2371, 0.3034],
         [0.6774, 0.5734],
         [0.5934, 0.3888]],

        [[0.4498, 0.9991],
         [0.3266, 0.3257],
         [0.6172, 0.6257]],

        [[0.6679, 0.6316],
         [0.3658, 0.1805],
         [0.6686, 0.5832]],

        [[0.5331, 0.6220],
         [0.2462, 0.6688],
         [0.4394, 0.8337]]])
torch.Size([4, 3, 2])


In [ ]:
a = torch.rand(5,3)
a

tensor([[0.9507, 0.3967, 0.4857],
        [0.5172, 0.7163, 0.2444],
        [0.2352, 0.9772, 0.9995],
        [0.9181, 0.5706, 0.2527],
        [0.2734, 0.0090, 0.1224]])

In [ ]:
a = a.view(3,5)
a

tensor([[0.9507, 0.3967, 0.4857, 0.5172, 0.7163],
        [0.2444, 0.2352, 0.9772, 0.9995, 0.9181],
        [0.5706, 0.2527, 0.2734, 0.0090, 0.1224]])

In [ ]:
a = a.view(2,-1)
a

RuntimeError: ignored

In [ ]:
a = a.view(5,-1)
a

tensor([[0.9507, 0.3967, 0.4857],
        [0.5172, 0.7163, 0.2444],
        [0.2352, 0.9772, 0.9995],
        [0.9181, 0.5706, 0.2527],
        [0.2734, 0.0090, 0.1224]])

In [ ]:
a = torch.rand(3,2)
a

tensor([[0.0960, 0.4586],
        [0.5019, 0.7365],
        [0.5869, 0.2419]])

In [ ]:
torch.reshape(a, (2, 3))
print(a) # may or may not affcet a

tensor([[0.0960, 0.4586],
        [0.5019, 0.7365],
        [0.5869, 0.2419]])


In [ ]:
print(torch.reshape(a, (2, 3)))

tensor([[0.0960, 0.4586, 0.5019],
        [0.7365, 0.5869, 0.2419]])


In [ ]:
a = torch.tensor([[1,2], [3,4],[5,6]])
a

tensor([[1, 2],
        [3, 4],
        [5, 6]])

In [ ]:
a.size()

torch.Size([3, 2])

In [ ]:
a = a.resize_(2, 2)
a

tensor([[1, 2],
        [3, 4]])

In [ ]:
a = torch.tensor([[1,2], [3,4],[5,6]])

In [ ]:
a = a.resize(2,2)
a

/usr/local/lib/python3.7/dist-packages/torch/tensor.py:474: UserWarning: non-inplace resize is deprecated
  warnings.warn("non-inplace resize is deprecated")


RuntimeError: ignored

In [ ]:
a = a.resize_(4,2) # as the size is more than the actual size. Elemets are initialized with empty values
a

tensor([[         1,          2],
        [         3,          4],
        [         5,          6],
        [1566929017,          0]])

In [ ]:
a

NameError: ignored

In [ ]:
import torch
a = torch.rand(2,2)
b = torch.rand(2,2)
a,b

(tensor([[0.4915, 0.5330],
         [0.0325, 0.0811]]), tensor([[0.3958, 0.4814],
         [0.2754, 0.8465]]))

In [ ]:
print(a+b)

tensor([[0.8872, 1.0144],
        [0.3079, 0.9276]])


In [ ]:
print(a.add_(b))

tensor([[0.8872, 1.0144],
        [0.3079, 0.9276]])


In [ ]:
print(torch.add(a,b))

tensor([[1.2830, 1.4958],
        [0.5834, 1.7741]])


In [ ]:
print(torch.sum(a))

tensor(3.1371)


In [ ]:
a = torch.rand(2,5)
b = torch.rand(5,2)
print(a)
print(b)

tensor([[0.3698, 0.6144, 0.0390, 0.4955, 0.6452],
        [0.6687, 0.0240, 0.1775, 0.0379, 0.6804]])
tensor([[0.6576, 0.1527],
        [0.7916, 0.4459],
        [0.0785, 0.8021],
        [0.5803, 0.1109],
        [0.6473, 0.6018]])


In [ ]:
print(a*b)

RuntimeError: ignored

In [ ]:
print(torch.mm(a,b))

tensor([[1.4378, 0.8049],
        [0.9351, 0.6688]])


In [ ]:
print(torch.matmul(a,b))

tensor([[1.4378, 0.8049],
        [0.9351, 0.6688]])


In [ ]:
a = torch.randn(3)
a

tensor([ 1.3905, -2.1555,  0.9066])

In [ ]:
b= torch.randn(3)
b

tensor([0.7408, 0.3803, 0.0586])

In [ ]:
print(torch.mm(a,b)) # this is vector multiplication, which can't be done through torch.mm() function

RuntimeError: ignored

In [ ]:
print(torch.matmul(a,b))  # Vector multiplication is possible here

tensor(0.2635)


In [ ]:
a = torch.ones(3,4)
a

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
b = torch.ones(4)
print(b)
print(b.ndim)

tensor([1., 1., 1., 1.])
1


In [ ]:
c = torch.matmul(a,b) # while multiplying b is considered as (4,1) matrix. Therefore a(3,4) * b(4,1)  = a matrix of (3,1)
c

tensor([4., 4., 4.])

In [ ]:
c.ndim

1

In [ ]:
c

tensor([4., 4., 4.])

In [ ]:
a  = torch.rand(10,5,3,4)
print(a)

tensor([[[[0.4144, 0.6799, 0.7575, 0.2323],
          [0.5859, 0.0243, 0.9536, 0.2886],
          [0.8590, 0.8244, 0.0691, 0.6834]],

         [[0.9129, 0.3890, 0.4927, 0.8673],
          [0.6313, 0.2397, 0.1098, 0.4053],
          [0.4538, 0.3312, 0.0414, 0.0848]],

         [[0.2416, 0.1468, 0.1866, 0.8860],
          [0.2440, 0.3690, 0.3171, 0.1478],
          [0.8178, 0.2877, 0.6460, 0.1842]],

         [[0.8188, 0.5009, 0.1869, 0.0026],
          [0.5612, 0.2362, 0.7251, 0.6602],
          [0.0962, 0.7489, 0.6897, 0.2571]],

         [[0.9904, 0.4867, 0.2909, 0.1293],
          [0.0316, 0.6948, 0.2147, 0.2975],
          [0.1415, 0.8580, 0.1233, 0.9148]]],


        [[[0.7906, 0.0326, 0.0855, 0.6359],
          [0.6565, 0.2692, 0.2638, 0.1763],
          [0.4318, 0.5330, 0.9210, 0.2820]],

         [[0.7804, 0.5605, 0.8036, 0.6424],
          [0.2046, 0.9740, 0.6037, 0.5989],
          [0.8997, 0.5641, 0.1344, 0.3181]],

         [[0.4280, 0.5675, 0.9688, 0.3090],
          [0.872

In [ ]:
b = torch.rand(4,3)
b

tensor([[0.6430, 0.1357, 0.3913],
        [0.4428, 0.1390, 0.1808],
        [0.8119, 0.3394, 0.5301],
        [0.0868, 0.0140, 0.5081]])

In [ ]:
print(a.size())
print(b.size())
print(torch.matmul(a,b).size())

torch.Size([10, 5, 3, 4])
torch.Size([4, 3])
torch.Size([10, 5, 3, 3])


In [2]:
a = torch.rand(3,4)
a

tensor([[0.0937, 0.2681, 0.2239, 0.7707],
        [0.1225, 0.6607, 0.9547, 0.8907],
        [0.1621, 0.6852, 0.9429, 0.1397]])

In [3]:
a[0]

tensor([0.0937, 0.2681, 0.2239, 0.7707])

In [4]:
a[1]

tensor([0.1225, 0.6607, 0.9547, 0.8907])

In [5]:
a[-1]

tensor([0.1621, 0.6852, 0.9429, 0.1397])

In [6]:
a[0:2]

tensor([[0.0937, 0.2681, 0.2239, 0.7707],
        [0.1225, 0.6607, 0.9547, 0.8907]])

In [7]:
a[:2]

tensor([[0.0937, 0.2681, 0.2239, 0.7707],
        [0.1225, 0.6607, 0.9547, 0.8907]])

In [8]:
a[:]

tensor([[0.0937, 0.2681, 0.2239, 0.7707],
        [0.1225, 0.6607, 0.9547, 0.8907],
        [0.1621, 0.6852, 0.9429, 0.1397]])

In [10]:
a[:, 0]

tensor([0.0937, 0.1225, 0.1621])

In [11]:
a[-1, 1]

tensor(0.6852)

In [12]:
a[2,:]

tensor([0.1621, 0.6852, 0.9429, 0.1397])

In [14]:
a = torch.rand(2,3)
a

tensor([[0.4880, 0.7615, 0.5573],
        [0.4359, 0.8627, 0.5990]])

In [18]:
b = torch.rand(5,3)
b

tensor([[0.3273, 0.1436, 0.8973],
        [0.8552, 0.7051, 0.8646],
        [0.1077, 0.9000, 0.1154],
        [0.4958, 0.1932, 0.5687],
        [0.9728, 0.0265, 0.1726]])

In [19]:
torch.cat((a,b,a))

tensor([[0.4880, 0.7615, 0.5573],
        [0.4359, 0.8627, 0.5990],
        [0.3273, 0.1436, 0.8973],
        [0.8552, 0.7051, 0.8646],
        [0.1077, 0.9000, 0.1154],
        [0.4958, 0.1932, 0.5687],
        [0.9728, 0.0265, 0.1726],
        [0.4880, 0.7615, 0.5573],
        [0.4359, 0.8627, 0.5990]])

In [20]:
torch.cat((a,b),0) #dim=0 means will contenate row wise. No of columns should match

tensor([[0.4880, 0.7615, 0.5573],
        [0.4359, 0.8627, 0.5990],
        [0.3273, 0.1436, 0.8973],
        [0.8552, 0.7051, 0.8646],
        [0.1077, 0.9000, 0.1154],
        [0.4958, 0.1932, 0.5687],
        [0.9728, 0.0265, 0.1726]])

In [23]:
torch.cat((a,b),1) #dim=1 means will contenate column wise. No. of rows should match

RuntimeError: ignored

In [24]:
import numpy as np

In [28]:
a = np.random.rand(2,3)

In [29]:
a

array([[0.01965746, 0.908476  , 0.14507753],
       [0.34395059, 0.60443526, 0.82275613]])

In [30]:
b  = torch.from_numpy(a)

In [31]:
b

tensor([[0.0197, 0.9085, 0.1451],
        [0.3440, 0.6044, 0.8228]], dtype=torch.float64)

In [32]:
b[0,0] = 2.1

In [33]:
a

array([[2.1       , 0.908476  , 0.14507753],
       [0.34395059, 0.60443526, 0.82275613]])

In [34]:
b.numpy()

array([[2.1       , 0.908476  , 0.14507753],
       [0.34395059, 0.60443526, 0.82275613]])

In [35]:
torch.cuda.is_available()

True

In [36]:
x = torch.rand(5,3)

In [39]:
print("X in CPU memory\n", x)

X in CPU memory
 tensor([[0.7826, 0.3270, 0.9097],
        [0.4558, 0.2754, 0.6370],
        [0.0290, 0.8827, 0.9117],
        [0.7088, 0.3631, 0.6320],
        [0.6894, 0.3060, 0.5287]], device='cuda:0')


In [40]:
device = 'cuda' if torch.cuda.is_available() else 'cpu'

if torch.cuda.is_available():
  y = torch.ones_like(x, device=device)
  print("y in CPU memory\n", y)
  x = x.to(device)
  print("x in GPU memory\n", x)
  z = x + y
  print("Z in GPU Memory after addition\n", z)
  print(z.to("cpu", torch.double))



y in CPU memory
 tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], device='cuda:0')
x in GPU memory
 tensor([[0.7826, 0.3270, 0.9097],
        [0.4558, 0.2754, 0.6370],
        [0.0290, 0.8827, 0.9117],
        [0.7088, 0.3631, 0.6320],
        [0.6894, 0.3060, 0.5287]], device='cuda:0')
Z in GPU Memory after addition
 tensor([[1.7826, 1.3270, 1.9097],
        [1.4558, 1.2754, 1.6370],
        [1.0290, 1.8827, 1.9117],
        [1.7088, 1.3631, 1.6320],
        [1.6894, 1.3060, 1.5287]], device='cuda:0')
tensor([[1.7826, 1.3270, 1.9097],
        [1.4558, 1.2754, 1.6370],
        [1.0290, 1.8827, 1.9117],
        [1.7088, 1.3631, 1.6320],
        [1.6894, 1.3060, 1.5287]], dtype=torch.float64)


In [41]:
x = torch.rand(5,3)
print("X in CPU memory\n", x)

device = 'cuda' if torch.cuda.is_available() else 'cpu'

if torch.cuda.is_available():
  y = torch.ones_like(x, device=device)
  print("y in CPU memory\n", y)
  #x = x.to(device)
  #print("x in GPU memory\n", x)
  z = x + y
  print("Z in GPU Memory after addition\n", z)
  print(z.to("cpu", torch.double))

X in CPU memory
 tensor([[0.0030, 0.7966, 0.2486],
        [0.6992, 0.2347, 0.6618],
        [0.8585, 0.4498, 0.9563],
        [0.8357, 0.1753, 0.6884],
        [0.9853, 0.8268, 0.2586]])
y in CPU memory
 tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], device='cuda:0')


RuntimeError: ignored

In [2]:
#Broadcasting
import torch
a = torch.rand(10,2)
a

tensor([[0.9342, 0.6886],
        [0.9778, 0.8324],
        [0.3404, 0.9841],
        [0.3265, 0.6654],
        [0.3988, 0.1802],
        [0.5194, 0.7650],
        [0.3756, 0.0986],
        [0.0386, 0.4212],
        [0.4988, 0.4980],
        [0.1082, 0.0527]])

In [3]:
b = torch.rand(2)
b

tensor([0.9018, 0.9006])

In [4]:
a - b

tensor([[ 0.0324, -0.2120],
        [ 0.0760, -0.0682],
        [-0.5614,  0.0835],
        [-0.5752, -0.2352],
        [-0.5030, -0.7205],
        [-0.3824, -0.1356],
        [-0.5261, -0.8020],
        [-0.8632, -0.4795],
        [-0.4030, -0.4027],
        [-0.7935, -0.8479]])

In [1]:
#Exercise  No. 1

In [2]:
import torch

In [21]:
a = torch.rand(3,4)
print(a)
print(a.shape)

b = torch.transpose(a,  0, 1)
print(b)
print(b.shape)

print(a.mm(b))

tensor([[0.5206, 0.9512, 0.2637, 0.4085],
        [0.8822, 0.0552, 0.8037, 0.8172],
        [0.6582, 0.3209, 0.2087, 0.0369]])
torch.Size([3, 4])
tensor([[0.5206, 0.8822, 0.6582],
        [0.9512, 0.0552, 0.3209],
        [0.2637, 0.8037, 0.2087],
        [0.4085, 0.8172, 0.0369]])
torch.Size([4, 3])
tensor([[1.4122, 1.0575, 0.7180],
        [1.0575, 2.0952, 0.7963],
        [0.7180, 0.7963, 0.5811]])


In [22]:
#Exercise No. 2

In [25]:
a = torch.eye(4,4)
print(a)
b = torch.rand(4,4)
print(b)

c = a.add_(b)
print(c)

tensor([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]])
tensor([[0.7184, 0.8971, 0.3068, 0.0845],
        [0.4880, 0.4216, 0.2977, 0.2992],
        [0.3846, 0.1775, 0.5848, 0.8377],
        [0.8419, 0.4522, 0.7191, 0.0569]])
tensor([[1.7184, 0.8971, 0.3068, 0.0845],
        [0.4880, 1.4216, 0.2977, 0.2992],
        [0.3846, 0.1775, 1.5848, 0.8377],
        [0.8419, 0.4522, 0.7191, 1.0569]])
